name: flutter_restaruant
description: Yelp restaurant searching in Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.4+21

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter_platform_widgets: ^3.3.5
  event_bus: ^2.0.0
  flutter_tags: ^1.0.0-nullsafety.1
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  geolocator: ^9.0.2
  image_picker: ^1.0.2
  camera: ^0.10.5+2
  sprintf: ^7.0.0
  flutter_inappwebview: ^5.7.2+3
  url_launcher: ^6.1.12
  fluttertoast: ^8.2.2
  settings_ui: ^2.0.2
  local_auth: ^2.1.6
  package_info_plus: ^4.1.0
  google_maps_flutter: ^2.4.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7

  dio: ^5.3.2
  retrofit: ^4.0.1
  logger: ^2.0.1

  firebase_core: ^2.15.0
  google_mobile_ads: ^3.0.0
  flutter_local_notifications: ^9.6.0
  firebase_analytics: ^10.4.4
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  firebase_auth: ^4.7.2
  firebase_messaging: ^14.6.5

  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^4.1.2
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  flutter_signin_button: ^2.0.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

dev_dependencies:
  equatable: any
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.8
  json_serializable: ^6.1.5

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/empty.png
    - images/icon_signinup_icon.gif
    - images/icon_setting_icon.gif
    - images/Star_rating_0.5_of_5.png
    - images/Star_rating_0_of_5.png
    - images/Star_rating_1.5_of_5.png
    - images/Star_rating_1_of_5.png
    - images/Star_rating_2.5_of_5.png
    - images/Star_rating_2_of_5.png
    - images/Star_rating_3.5_of_5.png
    - images/Star_rating_3_of_5.png
    - images/Star_rating_4.5_of_5.png
    - images/Star_rating_4_of_5.png
    - images/Star_rating_5_of_5.png
    - images/launch_image.png
    - images/ic_favor_empty.png
    - images/ic_favor_fill.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
